<?php

$kapsis = [
"AgADBAADn7AxG6nuKVMf15q_cOj7c0CQoBsABAEAAwIAA3gAAwEhAQABFgQ",
"AgADBAADoLAxG6nuKVNa5QZx7aBfG-t8qBsABAEAAwIAA3kAA4WUAQABFgQ",
"AgADBAADobAxG6nuKVPQCMsYloMjdusssRoABAEAAwIAA3gAA16SBAABFgQ",
"AgADBAADorAxG6nuKVPLS542zyWhbnsbsRoABAEAAwIAA3kAA7eYBAABFgQ",
"AgADBAADMrExG1R_IVPuJgSZfB2nHwLcLBsABAEAAwIAA3kAA38SBwABFgQ",
];

?>
